### ISSUE TITLE
Implematar CRUD Funcionario BuscarPorId

### ISSUE THREAD

**Issue by maxwesleyus** [Pro-Redfield/Pjt101-HospSExp#3]
*fazer após função busca dependentes por funcionarioid estiver pronta.

Criar em funcionarioDAO o método burca por id.
Implemantar classe , TestFuncionarioBuscaPorId no pacote FuncionarioTest

O resultado deve exibir as informações do Funcionário e nome dos seus dependentes.

**Comment by neuraman** [comment]
Implementado no commit 496543df59f87eb502e61d794c7ce33181c68d74
