### ISSUE TITLE
Implematar CRUD Funcionario Delete

### ISSUE THREAD

**Issue by maxwesleyus** [Pro-Redfield/Pjt101-HospSExp#4]
Criar em funcionarioDAO o método Delete.
Implemantar classe , TestFuncionarioDelete no pacote FuncionarioTest

O resultado deve deletar o funcionário que o id foi passado.

**Comment by neuraman** [comment]
Função implementada no commit fe8c0f8c5e7b04aa6046b53317e05d48b1d1c557
