### ISSUE TITLE
Implematar CRUD Funcionario update

### ISSUE THREAD

**Issue by maxwesleyus** [Pro-Redfield/Pjt101-HospSExp#5]
Criar em funcionarioDAO o método Update.
Implemantar classe , TestFuncionarioUpdate no pacote FuncionarioTest

O resultado deve alterar as informações do Funcionário cujo o valo do id foi passado.

**Comment by neuraman** [comment]
Commit  f292ba8a074adf8f89a85599654fc364a7dcbedd na branch connectionPool.
