### ISSUE TITLE
Implematar CRUD Funcionario Listar

### ISSUE THREAD

**Issue by maxwesleyus** [Pro-Redfield/Pjt101-HospSExp#6]
Criar em funcionarioDAO o método ListarFun.
Implemantar classe , TestFuncionarioListarFunDep no pacote FuncionarioTest

O resultado deve listar as informações dos Funcionários.

**Comment by neuraman** [comment]
Função implementada no commit 16addae9a27a271aa341173ce2490cc176ffc62d
